version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    user: app
    command: "true"
    links:
      - db
    env_file:
      - backend.env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - DATABASE_URL=postgres://postgres@db/postgres
      - DEBUG=True
      - SECRET_KEY=59114b6a-2858-4caf-8878-482a24ee9542
      - DJANGO_LOG_LEVEL=DEBUG
      - DJANGO_LOG_FORMAT=json
      - DJANGO_SETTINGS_MODULE=backend.settings.local

  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"
    user: app
    volumes:
      - .:/app
    command: dev
    links:
      - db
    env_file:
      - backend.env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - DATABASE_URL=postgres://postgres@db/postgres
      - DEBUG=True
      - SECRET_KEY=59114b6a-2858-4caf-8878-482a24ee9542
      - DJANGO_LOG_LEVEL=DEBUG
      - DJANGO_LOG_FORMAT=json
      - DJANGO_SETTINGS_MODULE=backend.settings.local

  db:
    image: postgres:9.5.12
